### ISSUE TITLE
profile performance on mainnet full block template generation

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-geth-old#15]

**Comment by jparyani** [comment]
Still doing more performance measuring, but on a t3.large aws instance, I'm seeing around ~10000 transactions per second (where the tx is just a simple sending of ETH). This is just the time it takes to calculate the flashbots bundle and is a rough approximation of the added latency.

**Comment by thegostep** [comment]
moved to https://github.com/flashbots/mev-geth/issues/3
