### ISSUE TITLE
Setup environment for integration test

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-geth-old#8]
- [ ] docker compose with 1 regular geth node and 1 mev-geth node peer on local testnet
- [ ] simulate sending variety of different bundles and evaluate execution

**Comment by gakonst** [comment]
I'm working on the image, should have something tomorrow midday. @jparyani will let you know.

**Comment by thegostep** [comment]
Moved to https://github.com/flashbots/mev-geth/issues/1
